INSERT INTO PUBLIC.CATEGORY (CATEGORY_NAME) VALUES ('Health');
INSERT INTO PUBLIC.CATEGORY (CATEGORY_NAME) VALUES ('Relationship');
INSERT INTO PUBLIC.CATEGORY (CATEGORY_NAME) VALUES ('Education');
INSERT INTO PUBLIC.CATEGORY (CATEGORY_NAME) VALUES ('Business');

INSERT INTO PUBLIC.TAG (TAG_NAME) VALUES ('Tutorial');
INSERT INTO PUBLIC.TAG (TAG_NAME) VALUES ('Podcast');
INSERT INTO PUBLIC.TAG (TAG_NAME) VALUES ('Steven Bartlett');
INSERT INTO PUBLIC.TAG (TAG_NAME) VALUES ('Alex Hormozi');
INSERT INTO PUBLIC.TAG (TAG_NAME) VALUES ('Codie Sanchez');
INSERT INTO PUBLIC.TAG (TAG_NAME) VALUES ('Daniel Priestley');
INSERT INTO PUBLIC.TAG (TAG_NAME) VALUES ('Jordan Peterson');
INSERT INTO PUBLIC.TAG (TAG_NAME) VALUES ('Andrew Huberman');

INSERT INTO PUBLIC.LINK (ADDRESS, DESCRIPTION, CREATED_AT, WORKFLOW_STATUS, VISIBILITY, CATEGORY_ID) VALUES ('https://www.youtube.com/watch?v=uTfxvs-s8EY', 'Bookmark Manager Tutorial ', '2025-08-20 18:22:52.000000', 'waiting', 'private', 3);
INSERT INTO PUBLIC.LINK (ADDRESS, DESCRIPTION, CREATED_AT, WORKFLOW_STATUS, VISIBILITY, CATEGORY_ID) VALUES ('https://www.youtube.com/watch?v=hVlAOIUA71Y', 'The Real Reason You’re Still Broke! (and how to escape it) ', '2025-08-20 18:22:58.000000', 'waiting', 'private', 4);
INSERT INTO PUBLIC.LINK (ADDRESS, DESCRIPTION, CREATED_AT, WORKFLOW_STATUS, VISIBILITY, CATEGORY_ID) VALUES ('https://www.youtube.com/watch?v=K0hkhbGYaGQ', 'How to Best Guide Your Life Decisions & Path ', '2025-08-20 18:23:01.000000', 'waiting', 'private', 2);

INSERT INTO PUBLIC.LINK_TAG (TAG_ID, LINK_ID) VALUES (1, 1);
INSERT INTO PUBLIC.LINK_TAG (TAG_ID, LINK_ID) VALUES (2, 2);
INSERT INTO PUBLIC.LINK_TAG (TAG_ID, LINK_ID) VALUES (3, 2);
INSERT INTO PUBLIC.LINK_TAG (TAG_ID, LINK_ID) VALUES (4, 2);
INSERT INTO PUBLIC.LINK_TAG (TAG_ID, LINK_ID) VALUES (5, 2);
INSERT INTO PUBLIC.LINK_TAG (TAG_ID, LINK_ID) VALUES (6, 2);
INSERT INTO PUBLIC.LINK_TAG (TAG_ID, LINK_ID) VALUES (2, 3);
INSERT INTO PUBLIC.LINK_TAG (TAG_ID, LINK_ID) VALUES (7, 3);
INSERT INTO PUBLIC.LINK_TAG (TAG_ID, LINK_ID) VALUES (8, 3);
